name: Release Production
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version to release"
      issue-number:
        type: number
        required: true
        description: "Release Issue number id"

jobs:
  run_docker:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo groupadd docker
            sudo usermod -aG docker ${USER}
            docker login --username oauth --password ${{ secrets.YANDEX_OAUTH }} cr.yandex
            docker pull cr.yandex/${{secrets.CR_ID}}/app:${{ inputs.version }}_latest
            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker run -d --restart unless-stopped -p 3000:3000 cr.yandex/${{secrets.CR_ID}}/app:${{ inputs.version }}_latest

  add_issue_comment:
    needs: [run_docker]
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{inputs.issue-number}}
          body: |
            **Deploy to production**:
            - Date: $(date)
            - Author: ${{ github.triggering_actor }}