name: Release Production
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version to release"

jobs:
  run_docker:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy to prod
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo usermod -aG docker ${USER}
            docker login --username oauth --password ${{ secrets.YANDEX_OAUTH }} cr.yandex
            docker pull cr.yandex/${{secrets.CR_ID}}/app:${{ inputs.version }}_latest
            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker run -d --restart unless-stopped -p 3000:3000 cr.yandex/${{secrets.CR_ID}}/app:${{ inputs.version }}_latest
  
  add_issue_comment:
    needs: [run_docker]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4.1.7
        with:
          ref: release/${{ inputs.version }}
      - name: Configure Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Add issue comment
        run: |
          touch $ISSUE
          echo "**Deploy to production**" >> $ISSUE
          echo "- Date: $(date)" >> $ISSUE
          echo "- Author: ${{ github.triggering_actor }}" >> $ISSUE
          number=$(gh issue list --label "release ${{ github.event.inputs.release_version }}" --json number --jq '.[0].number')
          gh issue comment "$number" --body-file "$ISSUE"
          rm $ISSUE
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE: issue.txt